version: "3.8"
services:
    nodeserver:
        build:
            context: ./app/server
        ports:
            - "5000:5000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
        volumes:
            - ./app/static_client_bind:/usr/share/nginx/html